In [10]:
import numpy as np

a = np.array([(1,2,3),(4,5,6),(8,9,0)])
print("Array:")
print(a)
print("Number of Items: " )
print(a.itemsize)
print("Shape :")
print(a.shape)


Array:
[[1 2 3]
 [4 5 6]
 [8 9 0]]
Number of Items: 
4
Shape :
(3, 3)


In [22]:
#slicing
print(a[1:,0:])
print(">>>>>")
print(a[:,2])

[[4 5 6]
 [8 9 0]]
>>>>>
[3 6 0]


In [32]:
print("before reshaping")
print(a)
a.reshape(9,1)
print("After reshaping")
print(a)


before reshaping
[[1 2 3]
 [4 5 6]
 [8 9 0]]
After reshaping
[[1 2 3]
 [4 5 6]
 [8 9 0]]


In [34]:
np.zeros(3)

array([0., 0., 0.])

In [35]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.random.random((2,3))


array([[0.54173898, 0.75460926, 0.23150024],
       [0.11134725, 0.84207067, 0.5931019 ]])

In [50]:
b = np.random.randint(0,10,(3,3))
print(a)
print("#########")
print(b)

[[1 2 3]
 [4 5 6]
 [8 9 0]]
#########
[[8 4 6]
 [1 9 3]
 [1 4 6]]


In [46]:
a.dot(b)

array([[31, 30, 21],
       [82, 75, 51],
       [90, 75, 41]])

In [53]:
#Column is known as axis 0
#row is known as axis 1
print("sum of rows of a:")
print(a.sum(axis=1))


sum of rows of a:
[ 6 15 17]


# I am Pandas

In [55]:
import pandas as pd

In [56]:
data = pd.read_csv('iris.csv')

In [57]:
data

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0           1.1          0.1     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
16            5.4          3.9           1.3          0.4     setosa
17            5.1          3.5           1.4          0.3     setosa
18            5.7          3.8           1.7          0.3     setosa
19            5.1          3.8           1.5          0.3     setosa
20            5.4          3.4           1.7          0.2     setosa
21            5.1          3.7           1.5          0.4     setosa
22            4.6          3.6           1.0          0.2     setosa
23            5.1          3.3           1.7          0.5     setosa
24            4.8          3.4           1.9          0.2     setosa
25            5.0          3.0           1.6          0.2     setosa
26            5.0          3.4           1.6          0.4     setosa
27            5.2          3.5           1.5          0.2     setosa
28            5.2          3.4           1.4          0.2     setosa
29            4.7          3.2           1.6          0.2     setosa
..            ...          ...           ...          ...        ...
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146

In [60]:
data.describe() # to get the description of the data

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [68]:
x = data.iloc[:,0:4]
x
y = data.iloc[:,4:]
y

species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
5       setosa
6       setosa
7       setosa
8       setosa
9       setosa
10      setosa
11      setosa
12      setosa
13      setosa
14      setosa
15      setosa
16      setosa
17      setosa
18      setosa
19      setosa
20      setosa
21      setosa
22      setosa
23      setosa
24      setosa
25      setosa
26      setosa
27      setosa
28      setosa
29      setosa
..         ...
120  virginica
121  virginica
122  virginica
123  virginica
124  virginica
125  virginica
126  virginica
127  virginica
128  virginica
129  virginica
130  virginica
131  virginica
132  virginica
133  virginica
134  virginica
135  virginica
136  virginica
137  virginica
138  virginica
139  virginica
140  virginica
141  virginica
142  virginica
143  virginica
144  virginica
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]

In [19]:
import numpy as np
x = np.array([(1,2,3),(4,5,6),(7,8,9)])
y = np.zeros(3)

for i in range(5):
    y = 5*x - y
print("y[5]  :\n")    
print(y)

y[5]  :

[[ 5. 10. 15.]
 [20. 25. 30.]
 [35. 40. 45.]]


# I am Simplpe Linear regression

In [29]:
import pandas as pd
data = pd.read_csv('iris.csv')
data.head(10)  #returns first 10 rows
data[["sepal_length","sepal_width","petal_width","petal_width"]] #returns data having these headings
# data.shape

sepal_length  sepal_width  petal_width  petal_width
0             5.1          3.5          0.2          0.2
1             4.9          3.0          0.2          0.2
2             4.7          3.2          0.2          0.2
3             4.6          3.1          0.2          0.2
4             5.0          3.6          0.2          0.2
5             5.4          3.9          0.4          0.4
6             4.6          3.4          0.3          0.3
7             5.0          3.4          0.2          0.2
8             4.4          2.9          0.2          0.2
9             4.9          3.1          0.1          0.1
10            5.4          3.7          0.2          0.2
11            4.8          3.4          0.2          0.2
12            4.8          3.0          0.1          0.1
13            4.3          3.0          0.1          0.1
14            5.8          4.0          0.2          0.2
15            5.7          4.4          0.4          0.4
16            5.4          3.9          0.4          0.4
17            5.1          3.5          0.3          0.3
18            5.7          3.8          0.3          0.3
19            5.1          3.8          0.3          0.3
20            5.4          3.4          0.2          0.2
21            5.1          3.7          0.4          0.4
22            4.6          3.6          0.2          0.2
23            5.1          3.3          0.5          0.5
24            4.8          3.4          0.2          0.2
25            5.0          3.0          0.2          0.2
26            5.0          3.4          0.4          0.4
27            5.2          3.5          0.2          0.2
28            5.2          3.4          0.2          0.2
29            4.7          3.2          0.2          0.2
..            ...          ...          ...          ...
120           6.9          3.2          2.3          2.3
121           5.6          2.8          2.0          2.0
122           7.7          2.8          2.0          2.0
123           6.3          2.7          1.8          1.8
124           6.7          3.3          2.1          2.1
125           7.2          3.2          1.8          1.8
126           6.2          2.8          1.8          1.8
127           6.1          3.0          1.8          1.8
128           6.4          2.8          2.1          2.1
129           7.2          3.0          1.6          1.6
130           7.4          2.8          1.9          1.9
131           7.9          3.8          2.0          2.0
132           6.4          2.8          2.2          2.2
133           6.3          2.8          1.5          1.5
134           6.1          2.6          1.4          1.4
135           7.7          3.0          2.3          2.3
136           6.3          3.4          2.4          2.4
137           6.4          3.1          1.8          1.8
138           6.0          3.0          1.8          1.8
139           6.9          3.1          2.1          2.1
140           6.7          3.1          2.4          2.4
141           6.9          3.1          2.3          2.3
142           5.8          2.7          1.9          1.9
143           6.8          3.2          2.3          2.3
144           6.7          3.3          2.5          2.5
145           6.7          3.0          2.3          2.3
146           6.3          2.5          1.9          1.9
147           6.5          3.0          2.0          2.0
148           6.2          3.4          2.3          2.3
149           5.9          3.0          1.8          1.8

[150 rows x 4 columns]

In [58]:
x = data.iloc[:,:-1] #slicing data into 2 sets of x and y
y = data.iloc[:,-1]

# Transfroming data in y into int values

In [63]:
from sklearn import preprocessing as p #this library converts strings into integers
le = p.LabelEncoder()
y = le.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [80]:
from sklearn.linear_model import LinearRegression

#creating linear regression object
model = LinearRegression()

#training the model using training data sets
model = LinearRegression().fit(x,y)

#train the model using the training sets
x1 = x.iloc[5,:]
# x1
model.predict([x1])

array([0.05680235])

# Linear  regression Fuel consumption example

In [19]:
import pandas as pd
from sklearn import preprocessing as p
from sklearn.linear_model import LinearRegression

## Preparing the data
data = pd.read_csv("FuelConsumption.csv")

x = data.iloc[:,:-1]
y = data.iloc[:,-1]

#transforming text into numbers
label = p.LabelEncoder()
li = ['MAKE','MODEL','VEHICLECLASS','TRANSMISSION','FUELTYPE']

for i in li:
    x[i] = label.fit_transform(x[i])

##Traning the model
model = LinearRegression()


In [14]:
x

MODELYEAR  MAKE  MODEL  VEHICLECLASS  ENGINESIZE  CYLINDERS  \
0          2014     0    329             0         2.0          4   
1          2014     0    329             0         2.4          4   
2          2014     0    330             0         1.5          4   
3          2014     0    389            11         3.5          6   
4          2014     0    483            11         3.5          6   
5          2014     0    490             2         3.5          6   
6          2014     0    578             2         3.5          6   
7          2014     0    579             2         3.7          6   
8          2014     0    579             2         3.7          6   
9          2014     0    591             0         2.4          4   
10         2014     0    591             0         2.4          4   
11         2014     0    591             0         3.5          6   
12         2014     1    212             3         5.9         12   
13         2014     1    479            10         5.9         12   
14         2014     1    600            13         4.7          8   
15         2014     1    600            13         4.7          8   
16         2014     1    601            13         4.7          8   
17         2014     1    601            13         4.7          8   
18         2014     1    602             3         5.9         12   
19         2014     2     72             0         2.0          4   
20         2014     2     73             0         2.0          4   
21         2014     2     73             0         2.0          4   
22         2014     2     74            10         2.0          4   
23         2014     2     75            10         2.0          4   
24         2014     2     75            10         2.0          4   
25         2014     2     76             2         2.0          4   
26         2014     2     76             2         3.0          6   
27         2014     2     77             2         3.0          6   
28         2014     2     78             2         3.0          6   
29         2014     2     79             2         3.0          6   
...         ...   ...    ...           ...         ...        ...   
1037       2014    37    342             0         2.0          4   
1038       2014    37    343             0         2.0          4   
1039       2014    37    343             0         2.0          4   
1040       2014    37    344             0         2.0          4   
1041       2014    37    344             0         2.0          4   
1042       2014    37    345             0         1.4          4   
1043       2014    37    424             2         1.8          4   
1044       2014    37    424             2         1.8          4   
1045       2014    37    424             2         2.5          5   
1046       2014    37    424             2         2.5          5   
1047       2014    37    424             2         3.6          6   
1048       2014    37    425             2         2.0          4   
1049       2014    37    425             2         2.0          4   
1050       2014    37    494             4         3.6          6   
1051       2014    37    574            11         2.0          4   
1052       2014    37    574            11         2.0          4   
1053       2014    37    575            11         2.0          4   
1054       2014    37    580            12         3.6          6   
1055       2014    37    581            12         3.0          6   
1056       2014    38    509             0         2.5          5   
1057       2014    38    510             0         2.5          5   
1058       2014    38    510             0         3.0          6   
1059       2014    38    513             2         3.2          6   
1060       2014    38    514             2         3.0          6   
1061       2014    38    623            11         3.2          6   
1062       2014    38    624            11         3.0          6   
1063


# Logistic Regression spam example

In [53]:
# import the libraries
import pandas as pd
from sklearn import preprocessing as p
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

#preparing the data
data = pd.read_csv("spam.csv")
x = data.iloc[:,:-1]
y = data.iloc[:,-1]

#split the data into training and testing set
xTrain,xTest,yTrain,yTest = train_test_split(x,y,test_size = 0.2,random_state =0)

#Training the model
model = LogisticRegression()
model.fit(xTrain,yTrain)

z = xTest.iloc[3,:]
#testing the model
model.predict([z]) #without probability
# model.predict_proba([z])  # with probability

#Measuring the model preformance

#using score method to get accuracy of model


array([1], dtype=int64)

# Feed forward neural network

In [13]:
import numpy as np

weights = np.random.random(2)  #creatig 2 random values for weights
biases = np.random.random(2)   #creating 2 random values for biases

#inputs
x1 = 0.34
x2 = 0.45

y1 = x1*weights[0] + biases[0]
y1 = np.round(y1,decimals = 2)
y1

0.47

In [15]:
a1 = 1/(1+ np.exp(-y1))
a1 = np.round(a1,decimals = 2)
a1

0.62

In [18]:
y2 = a1*weights[1]+ biases[1]
y2 = np.round(y2,decimals = 2)
y2

0.45

In [21]:
a2 = 1/(1+np.exp(-y2))
a2 = np.round(a2,decimals = 2)
a2

0.61

In [22]:
# optimized way of above code
w = np.random.random(3)
x = np.random.random(3)
b = np.random.random(3)

In [24]:
y = x*w+b
y = np.round(y,decimals = 2)
y

array([1.37, 0.39, 0.73])

In [27]:
a = 1/(1+np.exp(-y))
a = np.round(a,decimals=2)
a

array([0.8 , 0.6 , 0.67])

# Artificial Neural Networks

In [29]:
import keras

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [32]:
from keras.models import Sequential
from keras.layers import Dense